services:
    tp-ws-db:
        container_name: tp-ws-db
        image: mariadb:10.3
        ports:
            - "3306:3306"
        environment:
            - MARIADB_ROOT_PASSWORD=easyma
        volumes:
            - ./data/dev:/var/lib/mysql/
        networks:
          - local
    tp-ws-api:
        container_name: "tp-ws-api"
        image: citizen63000/ubuntu-php-mariadb:1.0
#        build: .
        depends_on:
            - tp-ws-db
        ports:
           - 8080:8080
        volumes:
           - ../:/var/www/app/
           - ./app.conf:/etc/apache2/sites-available/app.conf
           - ./ports.conf:/etc/apache2/ports.conf
        networks:
           - local
    tp-ws-phpmyadmin:
        container_name: "phpmyadmin"
        image: phpmyadmin
        depends_on:
            - tp-ws-db
        ports:
           - 8081:80
        environment:
          PMA_HOST: tp-ws-db
        networks:
           - local
networks:
  local:

#http://localhost:8080/api-doc/default